/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AppointmentRegistry__factory } from "./AppointmentRegistry__factory";
export { DoctorRegistry__factory } from "./DoctorRegistry__factory";
export { MedicalRecordRegistry__factory } from "./MedicalRecordRegistry__factory";
export { PatientRegistry__factory } from "./PatientRegistry__factory";
