/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AppointmentRegistry {
  export type AppointmentInfoStruct = {
    appointmentId: BytesLike;
    paciente: AddressLike;
    medico: AddressLike;
    fechaTimestamp: BigNumberish;
    estado: BigNumberish;
    creadoEn: BigNumberish;
  };

  export type AppointmentInfoStructOutput = [
    appointmentId: string,
    paciente: string,
    medico: string,
    fechaTimestamp: bigint,
    estado: bigint,
    creadoEn: bigint
  ] & {
    appointmentId: string;
    paciente: string;
    medico: string;
    fechaTimestamp: bigint;
    estado: bigint;
    creadoEn: bigint;
  };
}

export interface AppointmentRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "bookAppointment"
      | "confirmAppointment"
      | "doctorRegistry"
      | "getAppointment"
      | "getAppointmentsByMedico"
      | "getAppointmentsByPaciente"
      | "owner"
      | "patientRegistry"
      | "renounceOwnership"
      | "transferOwnership"
      | "updateAppointmentStatus"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AppointmentBooked"
      | "AppointmentStatusUpdated"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "bookAppointment",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmAppointment",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "doctorRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAppointment",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAppointmentsByMedico",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAppointmentsByPaciente",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "patientRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAppointmentStatus",
    values: [BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "bookAppointment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confirmAppointment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "doctorRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAppointment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAppointmentsByMedico",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAppointmentsByPaciente",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "patientRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateAppointmentStatus",
    data: BytesLike
  ): Result;
}

export namespace AppointmentBookedEvent {
  export type InputTuple = [
    appointmentId: BytesLike,
    paciente: AddressLike,
    medico: AddressLike,
    fechaTimestamp: BigNumberish
  ];
  export type OutputTuple = [
    appointmentId: string,
    paciente: string,
    medico: string,
    fechaTimestamp: bigint
  ];
  export interface OutputObject {
    appointmentId: string;
    paciente: string;
    medico: string;
    fechaTimestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AppointmentStatusUpdatedEvent {
  export type InputTuple = [appointmentId: BytesLike, estado: BigNumberish];
  export type OutputTuple = [appointmentId: string, estado: bigint];
  export interface OutputObject {
    appointmentId: string;
    estado: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AppointmentRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AppointmentRegistry;
  waitForDeployment(): Promise<this>;

  interface: AppointmentRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  bookAppointment: TypedContractMethod<
    [medico: AddressLike, fechaTimestamp: BigNumberish],
    [string],
    "nonpayable"
  >;

  confirmAppointment: TypedContractMethod<
    [appointmentId: BytesLike],
    [void],
    "nonpayable"
  >;

  doctorRegistry: TypedContractMethod<[], [string], "view">;

  getAppointment: TypedContractMethod<
    [appointmentId: BytesLike],
    [AppointmentRegistry.AppointmentInfoStructOutput],
    "view"
  >;

  getAppointmentsByMedico: TypedContractMethod<
    [medico: AddressLike],
    [string[]],
    "view"
  >;

  getAppointmentsByPaciente: TypedContractMethod<
    [paciente: AddressLike],
    [string[]],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  patientRegistry: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateAppointmentStatus: TypedContractMethod<
    [appointmentId: BytesLike, nuevoEstado: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "bookAppointment"
  ): TypedContractMethod<
    [medico: AddressLike, fechaTimestamp: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confirmAppointment"
  ): TypedContractMethod<[appointmentId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "doctorRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAppointment"
  ): TypedContractMethod<
    [appointmentId: BytesLike],
    [AppointmentRegistry.AppointmentInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAppointmentsByMedico"
  ): TypedContractMethod<[medico: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getAppointmentsByPaciente"
  ): TypedContractMethod<[paciente: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "patientRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateAppointmentStatus"
  ): TypedContractMethod<
    [appointmentId: BytesLike, nuevoEstado: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AppointmentBooked"
  ): TypedContractEvent<
    AppointmentBookedEvent.InputTuple,
    AppointmentBookedEvent.OutputTuple,
    AppointmentBookedEvent.OutputObject
  >;
  getEvent(
    key: "AppointmentStatusUpdated"
  ): TypedContractEvent<
    AppointmentStatusUpdatedEvent.InputTuple,
    AppointmentStatusUpdatedEvent.OutputTuple,
    AppointmentStatusUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "AppointmentBooked(bytes32,address,address,uint256)": TypedContractEvent<
      AppointmentBookedEvent.InputTuple,
      AppointmentBookedEvent.OutputTuple,
      AppointmentBookedEvent.OutputObject
    >;
    AppointmentBooked: TypedContractEvent<
      AppointmentBookedEvent.InputTuple,
      AppointmentBookedEvent.OutputTuple,
      AppointmentBookedEvent.OutputObject
    >;

    "AppointmentStatusUpdated(bytes32,uint8)": TypedContractEvent<
      AppointmentStatusUpdatedEvent.InputTuple,
      AppointmentStatusUpdatedEvent.OutputTuple,
      AppointmentStatusUpdatedEvent.OutputObject
    >;
    AppointmentStatusUpdated: TypedContractEvent<
      AppointmentStatusUpdatedEvent.InputTuple,
      AppointmentStatusUpdatedEvent.OutputTuple,
      AppointmentStatusUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
