/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace DoctorRegistry {
  export type DoctorInfoStruct = {
    colegiatura: string;
    especializacion: string;
    activo: boolean;
    registradoEn: BigNumberish;
    totalAtenciones: BigNumberish;
  };

  export type DoctorInfoStructOutput = [
    colegiatura: string,
    especializacion: string,
    activo: boolean,
    registradoEn: bigint,
    totalAtenciones: bigint
  ] & {
    colegiatura: string;
    especializacion: string;
    activo: boolean;
    registradoEn: bigint;
    totalAtenciones: bigint;
  };
}

export interface DoctorRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getAllDoctors"
      | "getDoctorInfo"
      | "incrementarAtenciones"
      | "isVerified"
      | "owner"
      | "registerDoctor"
      | "renounceOwnership"
      | "revokeDoctor"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DoctorRegistrado"
      | "DoctorRevocado"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getAllDoctors",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDoctorInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "incrementarAtenciones",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isVerified",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerDoctor",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeDoctor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAllDoctors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDoctorInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "incrementarAtenciones",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isVerified", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerDoctor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeDoctor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace DoctorRegistradoEvent {
  export type InputTuple = [
    medico: AddressLike,
    especializacion: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    medico: string,
    especializacion: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    medico: string;
    especializacion: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DoctorRevocadoEvent {
  export type InputTuple = [medico: AddressLike];
  export type OutputTuple = [medico: string];
  export interface OutputObject {
    medico: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DoctorRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): DoctorRegistry;
  waitForDeployment(): Promise<this>;

  interface: DoctorRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAllDoctors: TypedContractMethod<[], [string[]], "view">;

  getDoctorInfo: TypedContractMethod<
    [addr: AddressLike],
    [DoctorRegistry.DoctorInfoStructOutput],
    "view"
  >;

  incrementarAtenciones: TypedContractMethod<
    [medico: AddressLike],
    [void],
    "nonpayable"
  >;

  isVerified: TypedContractMethod<[addr: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  registerDoctor: TypedContractMethod<
    [medico: AddressLike, colegiatura: string, especializacion: string],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  revokeDoctor: TypedContractMethod<
    [medico: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAllDoctors"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getDoctorInfo"
  ): TypedContractMethod<
    [addr: AddressLike],
    [DoctorRegistry.DoctorInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "incrementarAtenciones"
  ): TypedContractMethod<[medico: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isVerified"
  ): TypedContractMethod<[addr: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerDoctor"
  ): TypedContractMethod<
    [medico: AddressLike, colegiatura: string, especializacion: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeDoctor"
  ): TypedContractMethod<[medico: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "DoctorRegistrado"
  ): TypedContractEvent<
    DoctorRegistradoEvent.InputTuple,
    DoctorRegistradoEvent.OutputTuple,
    DoctorRegistradoEvent.OutputObject
  >;
  getEvent(
    key: "DoctorRevocado"
  ): TypedContractEvent<
    DoctorRevocadoEvent.InputTuple,
    DoctorRevocadoEvent.OutputTuple,
    DoctorRevocadoEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "DoctorRegistrado(address,string,uint256)": TypedContractEvent<
      DoctorRegistradoEvent.InputTuple,
      DoctorRegistradoEvent.OutputTuple,
      DoctorRegistradoEvent.OutputObject
    >;
    DoctorRegistrado: TypedContractEvent<
      DoctorRegistradoEvent.InputTuple,
      DoctorRegistradoEvent.OutputTuple,
      DoctorRegistradoEvent.OutputObject
    >;

    "DoctorRevocado(address)": TypedContractEvent<
      DoctorRevocadoEvent.InputTuple,
      DoctorRevocadoEvent.OutputTuple,
      DoctorRevocadoEvent.OutputObject
    >;
    DoctorRevocado: TypedContractEvent<
      DoctorRevocadoEvent.InputTuple,
      DoctorRevocadoEvent.OutputTuple,
      DoctorRevocadoEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
