/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AppointmentRegistry } from "./AppointmentRegistry";
export type { DoctorRegistry } from "./DoctorRegistry";
export type { MedicalRecordRegistry } from "./MedicalRecordRegistry";
export type { PatientRegistry } from "./PatientRegistry";
