/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace MedicalRecordRegistry {
  export type MedicalRecordStruct = {
    recordId: BytesLike;
    hash: BytesLike;
    medico: AddressLike;
    paciente: AddressLike;
    tipo: BigNumberish;
    estado: BigNumberish;
    timestamp: BigNumberish;
    version: string;
    recordPrevioId: BytesLike;
  };

  export type MedicalRecordStructOutput = [
    recordId: string,
    hash: string,
    medico: string,
    paciente: string,
    tipo: bigint,
    estado: bigint,
    timestamp: bigint,
    version: string,
    recordPrevioId: string
  ] & {
    recordId: string;
    hash: string;
    medico: string;
    paciente: string;
    tipo: bigint;
    estado: bigint;
    timestamp: bigint;
    version: string;
    recordPrevioId: string;
  };
}

export interface MedicalRecordRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "doctorRegistry"
      | "getRecord"
      | "getRecordsByMedico"
      | "getRecordsByPaciente"
      | "owner"
      | "patientRegistry"
      | "registerCorrection"
      | "registerRecord"
      | "renounceOwnership"
      | "transferOwnership"
      | "updateStatus"
      | "verifyIntegrity"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CorrectionRegistered"
      | "OwnershipTransferred"
      | "RecordRegistered"
      | "StatusUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "doctorRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRecord",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecordsByMedico",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecordsByPaciente",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "patientRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerCorrection",
    values: [BytesLike, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerRecord",
    values: [BytesLike, AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateStatus",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyIntegrity",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "doctorRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRecord", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRecordsByMedico",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecordsByPaciente",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "patientRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerCorrection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyIntegrity",
    data: BytesLike
  ): Result;
}

export namespace CorrectionRegisteredEvent {
  export type InputTuple = [recordId: BytesLike, recordPrevioId: BytesLike];
  export type OutputTuple = [recordId: string, recordPrevioId: string];
  export interface OutputObject {
    recordId: string;
    recordPrevioId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecordRegisteredEvent {
  export type InputTuple = [
    recordId: BytesLike,
    medico: AddressLike,
    paciente: AddressLike,
    tipo: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    recordId: string,
    medico: string,
    paciente: string,
    tipo: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    recordId: string;
    medico: string;
    paciente: string;
    tipo: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StatusUpdatedEvent {
  export type InputTuple = [
    recordId: BytesLike,
    estado: BigNumberish,
    updatedBy: AddressLike
  ];
  export type OutputTuple = [
    recordId: string,
    estado: bigint,
    updatedBy: string
  ];
  export interface OutputObject {
    recordId: string;
    estado: bigint;
    updatedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MedicalRecordRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): MedicalRecordRegistry;
  waitForDeployment(): Promise<this>;

  interface: MedicalRecordRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  doctorRegistry: TypedContractMethod<[], [string], "view">;

  getRecord: TypedContractMethod<
    [recordId: BytesLike],
    [MedicalRecordRegistry.MedicalRecordStructOutput],
    "view"
  >;

  getRecordsByMedico: TypedContractMethod<
    [medico: AddressLike],
    [string[]],
    "view"
  >;

  getRecordsByPaciente: TypedContractMethod<
    [paciente: AddressLike],
    [string[]],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  patientRegistry: TypedContractMethod<[], [string], "view">;

  registerCorrection: TypedContractMethod<
    [hashNuevo: BytesLike, recordPrevioId: BytesLike, version: string],
    [string],
    "nonpayable"
  >;

  registerRecord: TypedContractMethod<
    [
      hash: BytesLike,
      paciente: AddressLike,
      tipo: BigNumberish,
      version: string
    ],
    [string],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateStatus: TypedContractMethod<
    [recordId: BytesLike, nuevoEstado: BigNumberish],
    [void],
    "nonpayable"
  >;

  verifyIntegrity: TypedContractMethod<
    [recordId: BytesLike, hashAVerificar: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "doctorRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getRecord"
  ): TypedContractMethod<
    [recordId: BytesLike],
    [MedicalRecordRegistry.MedicalRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRecordsByMedico"
  ): TypedContractMethod<[medico: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getRecordsByPaciente"
  ): TypedContractMethod<[paciente: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "patientRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerCorrection"
  ): TypedContractMethod<
    [hashNuevo: BytesLike, recordPrevioId: BytesLike, version: string],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerRecord"
  ): TypedContractMethod<
    [
      hash: BytesLike,
      paciente: AddressLike,
      tipo: BigNumberish,
      version: string
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateStatus"
  ): TypedContractMethod<
    [recordId: BytesLike, nuevoEstado: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyIntegrity"
  ): TypedContractMethod<
    [recordId: BytesLike, hashAVerificar: BytesLike],
    [boolean],
    "view"
  >;

  getEvent(
    key: "CorrectionRegistered"
  ): TypedContractEvent<
    CorrectionRegisteredEvent.InputTuple,
    CorrectionRegisteredEvent.OutputTuple,
    CorrectionRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RecordRegistered"
  ): TypedContractEvent<
    RecordRegisteredEvent.InputTuple,
    RecordRegisteredEvent.OutputTuple,
    RecordRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "StatusUpdated"
  ): TypedContractEvent<
    StatusUpdatedEvent.InputTuple,
    StatusUpdatedEvent.OutputTuple,
    StatusUpdatedEvent.OutputObject
  >;

  filters: {
    "CorrectionRegistered(bytes32,bytes32)": TypedContractEvent<
      CorrectionRegisteredEvent.InputTuple,
      CorrectionRegisteredEvent.OutputTuple,
      CorrectionRegisteredEvent.OutputObject
    >;
    CorrectionRegistered: TypedContractEvent<
      CorrectionRegisteredEvent.InputTuple,
      CorrectionRegisteredEvent.OutputTuple,
      CorrectionRegisteredEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RecordRegistered(bytes32,address,address,uint8,uint256)": TypedContractEvent<
      RecordRegisteredEvent.InputTuple,
      RecordRegisteredEvent.OutputTuple,
      RecordRegisteredEvent.OutputObject
    >;
    RecordRegistered: TypedContractEvent<
      RecordRegisteredEvent.InputTuple,
      RecordRegisteredEvent.OutputTuple,
      RecordRegisteredEvent.OutputObject
    >;

    "StatusUpdated(bytes32,uint8,address)": TypedContractEvent<
      StatusUpdatedEvent.InputTuple,
      StatusUpdatedEvent.OutputTuple,
      StatusUpdatedEvent.OutputObject
    >;
    StatusUpdated: TypedContractEvent<
      StatusUpdatedEvent.InputTuple,
      StatusUpdatedEvent.OutputTuple,
      StatusUpdatedEvent.OutputObject
    >;
  };
}
