/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as openzeppelin from "./@openzeppelin";
export type { openzeppelin };
import type * as contracts from "./contracts";
export type { contracts };
export * as factories from "./factories";
export type { Ownable } from "./@openzeppelin/contracts/access/Ownable";
export { Ownable__factory } from "./factories/@openzeppelin/contracts/access/Ownable__factory";
export type { AppointmentRegistry } from "./contracts/AppointmentRegistry";
export { AppointmentRegistry__factory } from "./factories/contracts/AppointmentRegistry__factory";
export type { DoctorRegistry } from "./contracts/DoctorRegistry";
export { DoctorRegistry__factory } from "./factories/contracts/DoctorRegistry__factory";
export type { MedicalRecordRegistry } from "./contracts/MedicalRecordRegistry";
export { MedicalRecordRegistry__factory } from "./factories/contracts/MedicalRecordRegistry__factory";
export type { PatientRegistry } from "./contracts/PatientRegistry";
export { PatientRegistry__factory } from "./factories/contracts/PatientRegistry__factory";
